### ISSUE TITLE
TopologyTester: fetch_application_logs should work for DISTRIBUTED and STREAMING_ANALYTICS_SERVICE

### ISSUE THREAD

**Issue by markheger** [IBMStreams/streamsx.topology#1610] opened 2018-04-19 10:07 UTC
If `always_collect_logs=True` then the tester should support to collect the logs in a local Streams instance.
Currently it is supported in Streaming Analytics Service only.

**Comment by ddebrunner** [comment] 2018-04-19 21:59
Duplicate of #1550.

**Closed by ddebrunner** 2018-04-19 21:59 UTC
