### ISSUE TITLE
Topology build failure: AttributeError: 'function' object has no attribute '__splpy_callable'

### ISSUE THREAD

**Issue by cancilla** [IBMStreams/streamsx.topology#507] opened 2016-08-30 14:20 UTC
I cloned the topology repository into my workspace and ran `ant`. I received the following error message: 

```
extract:
     [exec] Traceback (most recent call last):
     [exec]   File "/home/cancilla/git/streamsx.topology/com.ibm.streamsx.topology/bin/spl-python-extract.py", line 257, in <module>Checking  /home/cancilla/git/streamsx.topology/samples/python/com.ibm.streamsx.topology.pysamples/opt/python/streams/spl_mailsample.py for operators
     [exec]     process_operators(dynm, name, inspect.getmembers(dynm, inspect.isfunction))
     [exec] 
     [exec] com.ibm.streamsx.topology.pysamples.mail::simplesendmail
     [exec]    Send a simple email.
     [exec]   File "/home/cancilla/git/streamsx.topology/com.ibm.streamsx.topology/bin/spl-python-extract.py", line 236, in process_operators
     [exec]     common_tuple_operator(dynm, module, opname, opobj)
     [exec]   File "/home/cancilla/git/streamsx.topology/com.ibm.streamsx.topology/bin/spl-python-extract.py", line 217, in common_tuple_operator
     [exec]     copyCGT(opdir, ns, opname, opobj)
     [exec]   File "/home/cancilla/git/streamsx.topology/com.ibm.streamsx.topology/bin/spl-python-extract.py", line 131, in copyCGT
     [exec]     create_op_parameters(opmodel_xml, name, funcTuple)
     [exec]   File "/home/cancilla/git/streamsx.topology/com.ibm.streamsx.topology/bin/spl-python-extract.py", line 106, in create_op_parameters
     [exec]     if opObj.__splpy_callable == 'class':
     [exec] AttributeError: 'function' object has no attribute '__splpy_callable'
     [exec] Result: 1

```

**Comment by ddebrunner** [comment] 2016-08-30 15:26
Duplicate of #508

**Closed by ddebrunner** 2016-08-30 15:26 UTC
