### ISSUE TITLE
Running distributed tests leaves job running.

### ISSUE THREAD

**Issue by ddebrunner** [IBMStreams/streamsx.topology#178] opened 2015-09-01 22:05 UTC
I seem a single job with the application name com.ibm.streamsx.topology.tesat.api.isolationTest left running after running ant unittest.distributed.

**Comment by ddebrunner** [comment] 2015-09-25 21:21
Assign to @dlaboss as you've been working on this test recently, so it may already be fixed

**Comment by dlaboss** [comment] 2015-09-25 21:54
I'll look into it. I don't recall seeing that (looks like the only unit test that runs a job is testLowLatencySplit()) and it has a 10sec timeout specified.  
Recall if you were you able to cancel the job manually?
I've certainly seen times when Streams job cancellation just gets wedged.

**Comment by dlaboss** [comment] 2015-09-28 13:43
A run of distributed did leave a job running from IsolateTest.  The problem is that the test directly calls submit() instead of complete() so the canceljob never occurs.

**Comment by dlaboss** [comment] 2015-09-28 17:07
fixed by merge #227

**Closed by dlaboss** 2015-09-28 17:07 UTC
Labels: bug
